### ISSUE TITLE
python-pylint with pylint3: Checker definition probably flawed

### ISSUE THREAD

**Issue by quazgar** [flycheck/flycheck#1121]
In flycheck-mode with pylint3, I get loads of these error messages:

    Suspicious state from syntax checker python-pylint: Checker python-pylint returned non-zero exit code 1, but no errors from output: Traceback (most recent call last):
    File "/usr/bin/pylint3", line 3, in <module>
    run_pylint()
    File "/usr/lib/python3/dist-packages/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
    File "/usr/lib/python3/dist-packages/pylint/lint.py", line 1315, in __init__
    linter.check(args)
    File "/usr/lib/python3/dist-packages/pylint/lint.py", line 736, in check
    self._do_check(files_or_modules)
    File "/usr/lib/python3/dist-packages/pylint/lint.py", line 867, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
    File "/usr/lib/python3/dist-packages/pylint/lint.py", line 947, in check_astroid_module
    walker.walk(ast_node)
    File "/usr/lib/python3/dist-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
    File "/usr/lib/python3/dist-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
    File "/usr/lib/python3/dist-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
    File "/usr/lib/python3/dist-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
    File "/usr/lib/python3/dist-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
    File "/usr/lib/python3/dist-packages/pylint/utils.py", line 935, in walk
    cb(astroid)
    File "/usr/lib/python3/dist-packages/pylint/checkers/typecheck.py", line 337, in visit_attribute
    if re.match(pattern, node.attrname):
    File "/usr/lib/python3.5/re.py", line 163, in match
    return _compile(pattern, flags).match(string)
    File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
    File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
    File "/usr/lib/python3.5/sre_parse.py", line 822, in parse
    source = Tokenizer(str)
    File "/usr/lib/python3.5/sre_parse.py", line 225, in __init__
    self.__next()
    File "/usr/lib/python3.5/sre_parse.py", line 239, in __next
    self.string, len(self.string) - 1) from None
    sre_constants.error: bad escape (end of pattern) at position 0
    
    Checker definition probably flawed.

This happens with GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.21.5) on Debian testing.
I can reproduce it with `emacs -Q` as soon as I set

    (setq flycheck-python-pylint-executable "pylint3")

Pylint for Python2 does not show this error.

`flycheck-verify-setup` says:
    Syntax checkers for buffer myfile.py in python-mode:

    python-flake8 (disabled)
    - predicate:          t
    - executable:         Not found
    - configuration file: Not found

    python-pylint
    - predicate:          t
    - executable:         Found at /usr/bin/pylint3
    - configuration file: Found at "/home/quazgar/.pylintrc"

    python-pycompile
    - predicate:  t
    - executable: Found at /usr/bin/python

    Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
    checkers.

    --------------------

    Flycheck version: 30snapshot (package: 20160928.649)
    Emacs version:    24.5.1
    System:           x86_64-pc-linux-gnu
    Window system:    x

`pylint3` is at version 1.5.6.

**Comment by quazgar** [comment]
Sorry, the problem is with pylint, of course. https://github.com/PyCQA/pylint/issues/1122
