### ISSUE TITLE
KeyError: "default" on opening file

### ISSUE THREAD

**Issue by daedadu** [flycheck/flycheck#1266]
Hi when opening a python file I constantly get the above mentioned error.
This wasnt like that before, it started with a package update

Here is the trace

```Suspicious state from syntax checker python-flake8: Flycheck checker python-flake8 returned non-zero exit code 1, but its output contained no errors: 
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>                                                                                                                                    
    sys.exit(main())                                                                                                                                                                    
  File "/usr/local/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main                                                                                                    
    app.run(argv)                                                                                                                                                                       
  File "/usr/local/lib/python2.7/site-packages/flake8/main/application.py", line 328, in run                                                                                            
    self._run(argv)                                                                                                                                                                     
  File "/usr/local/lib/python2.7/site-packages/flake8/main/application.py", line 315, in _run                                                                                           
    self.initialize(argv)                                                                                                                                                               
  File "/usr/local/lib/python2.7/site-packages/flake8/main/application.py", line 300, in initialize                                                                                     
    self.make_formatter()                                                                                                                                                               
  File "/usr/local/lib/python2.7/site-packages/flake8/main/application.py", line 200, in make_formatter                                                                                 
    format_plugin, self.formatting_plugins['default']                                                                                                                                   
  File "/usr/local/lib/python2.7/site-packages/flake8/plugins/manager.py", line 345, in __getitem__                                                                                     
    return self.plugins[name]                                                                                                                                                           
KeyError: 'default'
```

and these are my versions

```
Syntax checkers for buffer spielwiese3.py in python-mode:

  python-flake8
    - may enable:         yes
    - executable:         Found at /usr/local/bin/flake8
    - configuration file: Not found

  python-pylint
    - may enable:         Automatically disabled!
    - executable:         Not found
    - configuration file: Not found

  python-pycompile
    - may enable: yes
    - executable: Found at /usr/local/bin/python

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 31snapshot (package: 20170601.608)
Emacs version:    25.2.1
System:           x86_64-apple-darwin15.6.0
Window system:    ns
```
any hints on how to solve this? It s pretty annoying as this is appearing on almost every action I m doing in the python file.

Regards

**Comment by daedadu** [comment]
So I found the solution here, which worked for me

[keyerror: 'defaul'](https://gitlab.com/pycqa/flake8/issues/320)
