### ISSUE TITLE
Rubocop >= 0.57 (including last version 0.58.2) shows errors when enabling `global-flycheck-mode` 

### ISSUE THREAD

**Issue by sadhu89** [flycheck/flycheck#1504]
* Some change were introduced in Rubocop 0.57 that Flycheck does not understand and shows the following error when Emacs is opened with the attached config.
(Notice I tried with several rubocop versions(including the last one 0.58.2) and I was able to isolate that the issue is happening only since rubocop version 0.57)

```
(use-package flycheck
  :ensure t
  :init
  (global-flycheck-mode))
```

```
Suspicious state from syntax checker ruby-rubocop: Flycheck checker ruby-rubocop returned non-zero exit code 2, but its output contained no errors: no implicit conversion of nil into String
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/path_util.rb:39:in `fnmatch?'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/path_util.rb:39:in `match_path?'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cop/cop.rb:214:in `block in file_name_matches_any?'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cop/cop.rb:208:in `any?'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cop/cop.rb:208:in `file_name_matches_any?'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cop/cop.rb:188:in `relevant_file?'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cop/cop.rb:193:in `excluded_file?'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:67:in `block in remove_irrelevant_cops'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:67:in `reject!'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:67:in `remove_irrelevant_cops'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:40:in `investigate'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cop/team.rb:114:in `investigate'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cop/team.rb:102:in `offenses'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:265:in `inspect_file'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:212:in `block in do_inspection_loop'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:244:in `block in iterate_until_no_changes'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:237:in `loop'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:237:in `iterate_until_no_changes'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:208:in `do_inspection_loop'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:111:in `block in file_offenses'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:129:in `file_offense_cache'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:109:in `file_offenses'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:100:in `process_file'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:75:in `each'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:75:in `reduce'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:75:in `each_inspected_file'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:67:in `inspect_files'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/runner.rb:39:in `run'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cli.rb:160:in `execute_runner'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cli.rb:88:in `execute_runners'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/lib/rubocop/cli.rb:41:in `run'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/exe/rubocop:13:in `block in <top (required)>'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/Users/sadhu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-0.57.0/exe/rubocop:12:in `<top (required)>'
/Users/sadhu/.rbenv/versions/2.5.0/bin/rubocop:23:in `load'
/Users/sadhu/.rbenv/versions/2.5.0/bin/rubocop:23:in `<main>'
```

It is also possible reproduce the error enabling manually `flycheck-mode` in `*scratch*`

* Flycheck setup from `M-x flycheck-verify-setup`: 
```
Syntax checkers for buffer *scratch* in ruby-mode:

  chef-foodcritic (disabled)
    - may enable: Automatically disabled!
    - predicate:  nil
    - executable: Not found

  ruby-rubocop
    - may enable:         yes
    - executable:         Found at /Users/sadhu/.rbenv/shims/rubocop
    - configuration file: Not found

  ruby-reek
    - may enable:         yes
    - executable:         Found at /Users/sadhu/.rbenv/shims/reek
    - configuration file: Not found

  ruby-rubylint (disabled)
    - may enable:         Automatically disabled!
    - executable:         Not found
    - configuration file: Not found

  ruby
    - may enable: yes
    - executable: Found at /Users/sadhu/.rbenv/shims/ruby

  ruby-jruby
    - may enable: Automatically disabled!
    - executable: Not found

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 32snapshot (package: 20180823.826)
Emacs version:    26.1
System:           x86_64-apple-darwin17.7.0
Window system:    mac
  ```
[emacsQ]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html

**Comment by fmdkdd** [comment]
That's curious.  Our CI is having [no trouble](https://travis-ci.org/flycheck/flycheck/jobs/424350796#L1258) checking with rubocop 0.58.2.

Do you have the error for any snippet of Ruby code?

**Comment by sadhu89** [comment]
It works fine when I enable `flycheck-mode` in any ruby file with M-x. The problem is when Emacs contains `global-flycheck-mode` in the config, then a failure is showed when Emacs is opened (independently which buffer it opens)

**Comment by fmdkdd** [comment]
I'm having trouble following.  You said:

> It is also possible reproduce the error enabling manually flycheck-mode in *scratch*

And your `*scratch*` buffer is in `ruby-mode`.  But you also said it works fine in that case:

> It works fine when I enable flycheck-mode in any ruby file with M-x

Can you give exact reproducing steps from `emacs -Q` for instance?  Or from a minimal configuration?

**Comment by cpitclaudel** [comment]
This looks like a rubocop bug]; if you have a repro, it would be worth reporting it upstream, since rubocop shouldn't print a backtrace like that.

**Comment by FLMFreddy** [comment]
Not sure if my situation is the same but I am getting the same stack trace. I get this only when using it in `org-edit-special` code block. It works perfectly fine otherwise. 

I am also curious if it is similar to the issue #1507 and that the fix might be something similar too #1695 

Thanks for taking the time to look at I would take a stab trying the approach myself but I am pretty new elisp and emacs.

**Comment by cpitclaudel** [comment]
@FLMFreddy can you open a separate issue, so we can work on it together?

**Comment by FLMFreddy** [comment]
Sure.
