### ISSUE TITLE
flake8 I/O operation on closed file

### ISSUE THREAD

**Issue by sivakov512** [flycheck/flycheck#1514]
* What you did, and what you expected to happen instead
Started emacs, opened any python file in project that has no errors. Expect nothing, but got error. When I run flake8 as cli with path to the same file i got no errors

* Whether and how you were able to [reproduce the issue in emacs -Q][emacsQ]
emacs -Q cannot reproduce the bug as flycheck is not setup.

* Your Flycheck setup from `M-x flycheck-verify-setup`
```
Syntax checkers for buffer test_sample.py in python-mode:

  python-flake8
    - may enable:         yes
    - executable:         Found at /home/sivakov512/Devel/Envs/clustermaster_updater/bin/python
    - configuration file: Not found
    - `flake8' module:    Found at "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/__init__.py"

  python-pylint
    - may enable:         Automatically disabled!
    - executable:         Found at /home/sivakov512/Devel/Envs/clustermaster_updater/bin/python
    - configuration file: Not found
    - `pylint' module:    Missing

  python-pycompile
    - may enable: yes
    - executable: Found at /home/sivakov512/Devel/Envs/clustermaster_updater/bin/python

  python-mypy
    - may enable:         Automatically disabled!
    - predicate:          t
    - executable:         Not found
    - configuration file: Not found

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20181018.1021)
Emacs version:    26.1
System:           x86_64-unknown-linux-gnu
Window system:    x

```

* Your operating system
VoidLinux
`Linux sl0 4.18.16_2 #1 SMP PREEMPT Mon Oct 29 16:10:00 UTC 2018 x86_64 GNU/Linux`

* Your Emacs version from `M-x emacs-version`
`GNU Emacs 26.1 (build 1, x86_64-unknown-linux-gnu, GTK+ Version 3.22.30) of 2018-07-26`

* Your Flycheck version from `M-x flycheck-version`
`Flycheck version: 32snapshot (package: 20181018.1021)`

* Error from *Messages* buffer
```
Suspicious state from syntax checker python-flake8: Flycheck checker python-flake8 returned non-zero exit code 1, but its output contained no errors: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/__main__.py", line 4, in <module>
    cli.main()
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/main/application.py", line 412, in run
    self._run(argv)
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/main/application.py", line 400, in _run
    self.run_checks()
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/main/application.py", line 318, in run_checks
    self.file_checker_manager.run()
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/checker.py", line 340, in run
    self.run_serial()
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/checker.py", line 324, in run_serial
    checker.run_checks()
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/checker.py", line 612, in run_checks
    self.run_ast_checks()
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/checker.py", line 520, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8_debugger.py", line 102, in run
    self.load_file()
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8_debugger.py", line 93, in load_file
    self.lines = pycodestyle.stdin_get_value().splitlines(True)
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/pycodestyle.py", line 1618, in stdin_get_value
    return TextIOWrapper(sys.stdin.buffer, errors='ignore').read()
ValueError: I/O operation on closed file

Try installing a more recent version of python-flake8, and please open a bug report if the issue persists in the latest release.  Thanks!
```

**Comment by fmdkdd** [comment]
Could you report your `flake8` version as well?

**Comment by sivakov512** [comment]
```
atomicwrites==1.2.1
attrs==18.2.0
flake8==3.6.0
flake8-commas==2.0.0
flake8-isort==2.5
isort==4.3.4
mccabe==0.6.1
more-itertools==4.3.0
pluggy==0.8.0
py==1.7.0
pycodestyle==2.4.0
pyflakes==2.0.0
pytest==3.9.3
six==1.11.0
testfixtures==6.3.0
```

I can reproduce the problem without `flake8` plugins also.

**Comment by sivakov512** [comment]
Perhaps this is a related problem - when creating and opening a new (not saved) file, I get this:
```
Suspicious state from syntax checker python-flake8: Flycheck checker python-flake8 returned non-zero exit code 1, but its output contained no errors: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/__main__.py", line 4, in <module>
    cli.main()
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/main/application.py", line 412, in run
    self._run(argv)
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/main/application.py", line 400, in _run
    self.run_checks()
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/main/application.py", line 318, in run_checks
    self.file_checker_manager.run()
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/checker.py", line 340, in run
    self.run_serial()
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/checker.py", line 324, in run_serial
    checker.run_checks()
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/checker.py", line 612, in run_checks
    self.run_ast_checks()
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8/checker.py", line 520, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/flake8_isort.py", line 65, in run
    settings_path=settings_file
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/isort/isort.py", line 113, in __init__
    self.file_encoding = coding_check(file_path)
  File "/home/sivakov512/Devel/Envs/clustermaster_updater/lib/python3.6/site-packages/isort/isort.py", line 1013, in coding_check
    with io.open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/sivakov512/Devel/Projects/yandex/clustermaster_updater/cm_updater/stdin'

Try installing a more recent version of python-flake8, and please open a bug report if the issue persists in the latest release.  Thanks!
```

**Comment by fmdkdd** [comment]
I'm sorry I cannot reproduce on my side.

From this error you have:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/sivakov512/Devel/Projects/yandex/clustermaster_updater/cm_updater/stdin'
```
It looks like flake8 is trying to open a `stdin` file instead of getting the file from standard input.  I have no idea why this would be the case.
