### ISSUE TITLE
Using eslint fails with a RangeError from the ignore package

### ISSUE THREAD

**Issue by so-o** [flycheck/flycheck#1846]
Here is a typical command run by flycheck:
```
/usr/bin/eslint --format\=json --stdin --stdin-filename /www/objectivejs.org/objectivejs/Objective.js < /www/objectivejs.org/objectivejs/Objective.js 
path should be a `path.relative()`d string, but got "../../../../www/objectivejs.org/objectivejs/Objective.js"
RangeError: path should be a `path.relative()`d string, but got "../../../../www/objectivejs.org/objectivejs/Objective.js"
    at throwError (/usr/share/nodejs/ignore/index.js:337:9)
    at checkPath (/usr/share/nodejs/ignore/index.js:356:12)
    at Ignore._test (/usr/share/nodejs/ignore/index.js:473:5)
    at Ignore.ignores (/usr/share/nodejs/ignore/index.js:512:17)
    at /usr/share/nodejs/ignore/index.js:516:26
    at Array.filter (<anonymous>)
    at Ignore.filter (/usr/share/nodejs/ignore/index.js:520:29)
    at IgnoredPaths.contains (/usr/share/nodejs/eslint/lib/ignored-paths.js:289:39)
    at CLIEngine.executeOnText (/usr/share/nodejs/eslint/lib/cli-engine.js:679:46)
    at Object.execute (/usr/share/nodejs/eslint/lib/cli.js:197:46)
```

The problem comes from the `--stdin --stdin-filename` logic. Something is wrong for the ignore package. If I run the same command without these options, no problem.

I tricked it by copying the command from flycheck.el and changing it my .emacs:

```
(require 'flycheck)

(flycheck-define-checker javascript-eslint
  "A Javascript syntax and style checker using eslint.

See URL `https://eslint.org/'."
  :command ("eslint" "--format=json"
            (option-list "--rulesdir" flycheck-eslint-rules-directories)
            (eval flycheck-eslint-args)
            source-original)
  :standard-input nil
  :error-parser flycheck-parse-eslint
  :enabled (lambda () (flycheck-eslint-config-exists-p))
  :modes (js-mode js-jsx-mode js2-mode js2-jsx-mode js3-mode rjsx-mode
                  typescript-mode)
  :working-directory flycheck-eslint--find-working-directory
  :verify
  (lambda (_)
    (let* ((default-directory
             (flycheck-compute-working-directory 'javascript-eslint))
           (have-config (flycheck-eslint-config-exists-p)))
      (list
       (flycheck-verification-result-new
        :label "config file"
        :message (if have-config "found" "missing or incorrect")
        :face (if have-config 'success '(bold error)))))))
```

Maybe using stding could be an option.

**Comment by cpitclaudel** [comment]
> Maybe using stding could be an option.

Do you mean *not* using stdin?

**Comment by so-o** [comment]
Yes! Why don't you pass the file name on the command line? I'm sure you have good reasons but there could be an option.

**Comment by cpitclaudel** [comment]
I think it would be better to report a bug to eslint.  The reason we use stdin is that we prefer not to create temporary files when checking unsaved file contents.

**Comment by so-o** [comment]
I'll try that and keep you updated.
