### ISSUE TITLE
flycheck ruby rubocop not working sometimes for both rspec tests and for regular ruby scripts

### ISSUE THREAD

**Issue by robbyoconnor** [flycheck/flycheck#695]
So I have a ruby project with rspec tests and am getting the following error: 

```
Suspicious state from syntax checker ruby-rubocop: Checker ruby-rubocop returned non-zero exit code 1, but no errors from output: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1
/home/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/psych.rb:370:in `parse'
/home/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
/home/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/psych.rb:318:in `parse'
/home/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/psych.rb:284:in `safe_load'
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/lib/rubocop/config_loader.rb:129:in `yaml_safe_load'
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/lib/rubocop/config_loader.rb:117:in `load_yaml_configuration'
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/lib/rubocop/config_loader.rb:27:in `load_file'
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/lib/rubocop/config_store.rb:23:in `options_config='
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/lib/rubocop/cli.rb:57:in `act_on_options'
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/lib/rubocop/cli.rb:22:in `run'
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/bin/rubocop:13:in `block in <top (required)>'
/home/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/bin/rubocop:12:in `<top (required)>'
/home/rob/.rvm/gems/ruby-2.2.0/bin/rubocop:23:in `load'
/home/rob/.rvm/gems/ruby-2.2.0/bin/rubocop:23:in `<main>'
/home/rob/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/home/rob/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

Checker definition probably flawed.
```

Also seems to happen with files like: 
```ruby
require_relative '../lib/game'
g = Game.new
g.ttt
```

And I get the following this: 

```
Suspicious state from syntax checker ruby-rubocop: Checker ruby-rubocop returned non-zero exit code 1, but no errors from output: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1
/home/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/psych.rb:370:in `parse'
/home/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
/home/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/psych.rb:318:in `parse'
/home/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/psych.rb:284:in `safe_load'
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/lib/rubocop/config_loader.rb:129:in `yaml_safe_load'
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/lib/rubocop/config_loader.rb:117:in `load_yaml_configuration'
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/lib/rubocop/config_loader.rb:27:in `load_file'
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/lib/rubocop/config_store.rb:23:in `options_config='
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/lib/rubocop/cli.rb:57:in `act_on_options'
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/lib/rubocop/cli.rb:22:in `run'
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/bin/rubocop:13:in `block in <top (required)>'
/home/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/home/rob/.rvm/gems/ruby-2.2.0/gems/rubocop-0.32.1/bin/rubocop:12:in `<top (required)>'
/home/rob/.rvm/gems/ruby-2.2.0/bin/rubocop:23:in `load'
/home/rob/.rvm/gems/ruby-2.2.0/bin/rubocop:23:in `<main>'
/home/rob/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/home/rob/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

Checker definition probably flawed.
```

**Comment by robbyoconnor** [comment]
Updated the description of the bug

**Comment by robbyoconnor** [comment]
This is an issue upstream and not with the checker itself, and am closing this -- I should have investigated farther but having this report is handy for others having this issue (at least I feel) :smile_cat:
