### ISSUE TITLE
eslint `... Cannot find module 'eslint-plugin-import' ... Checker definition probably flawed`

### ISSUE THREAD

**Issue by codedmart** [flycheck/flycheck#853]
I am seeing this issue with flycheck and eslint:
<img width="1279" alt="screen shot 2016-01-12 at 1 25 05 pm" src="https://cloud.githubusercontent.com/assets/40686/12275980/542e0fac-b930-11e5-904e-97cd2098fd5e.png">
I am using spacemacs on the develop branch so I believe I have a very recent version of flycheck. I am still fairly new to emacs/spacemacs so let me know if I can provide any other information.

**Comment by lunaryorn** [comment]
Hello,

thank you for reporting this issue.  We'll need more information to assess it, though.  Would you mind to

- run `C-c ! C-c` (aka `M-x flycheck-compile`) in the affected buffer and show the results,
- and run `M-x flycheck-version` and show the output?

**Comment by codedmart** [comment]
`C-c ! C-c` shows:
```
-*- mode: compilation; default-directory: "~/Work/lumi/lumi-flapjack/web/public/js/src/pages/" -*-
Compilation started at Wed Jan 13 05:56:35

eslint --format\=checkstyle --stdin --stdin-filename /Users/bmartin/Work/lumi/lumi-flapjack/web/public/js/src/pages/orders.js < /Users/bmartin/Work/lumi/lumi-flapjack/web/public/js/src/pages/orders.js
Cannot find module 'eslint-plugin-import'
Error: Cannot find module 'eslint-plugin-import'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:125:26
    at Array.forEach (native)
    at loadPlugins (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:116:21)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:204:5)
    at CLIEngine.executeOnText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:686:26)
    at Object.cli.execute (/usr/local/lib/node_modules/eslint/lib/cli.js:162:36)

Compilation exited abnormally with code 1 at Wed Jan 13 05:56:36
```
And `M-x flycheck-version`: `Flycheck version: 0.26snapshot (package: 20160111.1516)`

**Comment by lunaryorn** [comment]
Could you please run the command from your terminal?

**Comment by lunaryorn** [comment]
Also, please show the output of `C-c ! v` (`M-x flycheck-verify-setup`) in an affected buffer.

**Comment by codedmart** [comment]
Running the command from my terminal:
```
[~/Work/lumi/lumi-flapjack (feature/state_manager $=)]-> eslint --format\=checkstyle --stdin --stdin-filename /Users/bmartin/Work/lumi/lumi-flapjack/web/public/js/src/pages/orders.js < /Users/bmartin/Work/lumi/lumi-flapjack/web/public/js/src/pages/orders.js
Cannot find module 'eslint-plugin-import'
Error: Cannot find module 'eslint-plugin-import'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:125:26
    at Array.forEach (native)
    at loadPlugins (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:116:21)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:204:5)
    at CLIEngine.executeOnText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:686:26)
    at Object.cli.execute (/usr/local/lib/node_modules/eslint/lib/cli.js:162:36)
```
`C-c ! v` (`M-x flycheck-verify-setup`):
```
Syntax checkers for buffer orders.js in react-mode:

  javascript-eslint
    - predicate:  t
    - executable: Found at /usr/local/bin/eslint

Flycheck Mode is enabled.
```

**Comment by lunaryorn** [comment]
If it fails on the terminal too, it's not an Emacs/Flycheck issue at all.  It'd appear that your eslint installation is broken.  I'm sorry but I can't help you with that; I'm not a Javascript developer.

I'm closing this issue as invalid.

**Comment by codedmart** [comment]
Fair enough. Thanks for helping me look into it.

**Comment by lunaryorn** [comment]
At a wild guess, there's probably an `.eslintrc` somewhere in this project that loads enables the `import` plugin which you don't have installed.

But please understand that we can't really give you Javascript support. Thank you
